=== CrimeanPatterns/frontend/bundles/AwardWallet/MainBundle/Resources/config/urlRules.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:complexType name="universalLinksType">
        <xs:sequence>
            <xs:element name="host" type="hostType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="hostType">
        <xs:sequence>
            <xs:element name="path" type="pathType" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="scheme" type="xs:string" />
    </xs:complexType>

    <xs:complexType name="pathType">
        <xs:sequence>
            <xs:element name="route" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="regex" type="regexType" minOccurs="1" maxOccurs="unbounded"/>
            <xs:element name="handler" type="handlerType"/>
        </xs:sequence>
        <xs:attribute name="url" type="xs:string" use="required"/>
        <xs:attribute name="event" type="xs:string" use="required"/>
        <xs:attribute name="exclude-platform" type="platformType"/>
    </xs:complexType>

    <xs:complexType name="regexType">
        <xs:sequence>
            <xs:element name="set" type="setType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="url-part" type="urlPartType" default="path"/>
        <xs:attribute name="pattern" type="xs:string" use="required" />
    </xs:complexType>

    <xs:complexType name="handlerType">
        <xs:choice minOccurs="1" maxOccurs="1">
            <xs:element name="location" type="locationType"/>
            <xs:element name="state" type="stateType"/>
            <xs:element name="choose" type="chooseType"/>
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="setType">
        <xs:attribute name="name" type="xs:string" use="required" />
        <xs:attribute name="key" type="xs:string" use="required" />
    </xs:complexType>

    <xs:simpleType name="urlPartType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="url"/>
            <xs:enumeration value="scheme"/>
            <xs:enumeration value="host"/>
            <xs:enumeration value="path"/>
            <xs:enumeration value="hash"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="platformType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="ios"/>
            <xs:enumeration value="android"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="locationType">
        <xs:attribute name="url-part" type="urlPartType" use="required" />
    </xs:complexType>

    <xs:complexType name="stateType">
        <xs:sequence>
            <xs:element name="param" type="paramType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="route" type="xs:string" use="required" />
    </xs:complexType>

    <xs:complexType name="paramType">
        <xs:attribute name="name" type="xs:string" use="required" />
        <xs:attribute name="value" type="xs:string" use="required" />
    </xs:complexType>

    <xs:complexType name="chooseType">
        <xs:sequence>
            <xs:element name="when" type="whenType" maxOccurs="unbounded" />
            <xs:element name="otherwise" type="otherwiseType" minOccurs="0" maxOccurs="1" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="whenType">
        <xs:choice minOccurs="1" maxOccurs="1">
            <xs:element name="location" type="locationType"/>
            <xs:element name="state" type="stateType"/>
        </xs:choice>
        <xs:attribute name="var" type="xs:string" use="required" />
        <xs:attribute name="pattern" type="xs:string" use="required" />
    </xs:complexType>

    <xs:complexType name="otherwiseType">
        <xs:choice minOccurs="1" maxOccurs="1">
            <xs:element name="location" type="locationType"/>
            <xs:element name="state" type="stateType"/>
        </xs:choice>
    </xs:complexType>

    <xs:element name="universal-links" type="universalLinksType"/>
</xs:schema>

=== CrimeanPatterns/frontend/bundles/AwardWallet/MainBundle/Resources/config/urlRules.xml
<?xml version="1.0" encoding="UTF-8"?>
<universal-links xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urlRules.xsd">
    <host name="%host_name%" scheme="%host_scheme%">
        <path url="/account/list" event="accountList">
            <route>aw_account_list</route>
            <regex pattern="^/account/list$"/>
            <regex url-part="hash" pattern="^(?:\/\?(account|coupon)=(\d+)|.*)$">
                <set name="type" key="1"/>
                <set name="id" key="2"/>
            </regex>
            <handler>
                <choose>
                    <when var="type" pattern="^account$">
                        <state route="index.accounts.account-details">
                            <param name="Id" value="a{{id}}"/>
                        </state>
                    </when>
                    <when var="type" pattern="^coupon$">
                        <state route="index.accounts.account-details">
                            <param name="Id" value="c{{id}}"/>
                        </state>
                    </when>
                    <otherwise>
                        <state route="index.accounts.list"/>
                    </otherwise>
                </choose>
            </handler>
        </path>
        <path url="/awardBooking/requests" event="bookingList">
            <route>aw_booking_list_requests</route>
            <regex pattern="^/awardBooking/requests$"/>
            <handler>
                <state route="index.booking.list"/>
            </handler>
        </path>
        <path url="/awardBooking/view/*" event="bookingDetails">
            <route>aw_booking_view_index</route>
            <regex pattern="^/awardBooking/view/(\d+)$">
                <set name="requestId" key="1"/>
            </regex>
            <regex url-part="url" pattern="/awardBooking/view/\d+(?!.*(?:\?|&amp;)invoice=\d+)"/>
            <handler>
                <state route="index.booking.request.details">
                    <param name="Id" value="{{requestId}}"/>
                </state>
            </handler>
        </path>
        <path url="/account/select-provider" event="selectProvider">
            <route>aw_select_provider</route>
            <regex pattern="^/account/select-provider$"/>
            <regex url-part="hash" pattern="([^\/]*)$">
                <set name="page" key="1"/>
            </regex>
            <handler>
                <choose>
                    <when var="page" pattern=".+">
                        <state route="index.accounts.account-add">
                            <param name="providerId" value="{{page}}"/>
                        </state>
                    </when>
                    <otherwise>
                        <state route="index.accounts.add"/>
                    </otherwise>
                </choose>
            </handler>
        </path>
        <path url="/account/add/*" event="addAccount">
            <route>aw_account_add</route>
            <regex pattern="^/account/add/(\d+)$">
                <set name="providerId" key="1"/>
            </regex>
            <handler>
                <state route="index.accounts.account-add">
                    <param name="providerId" value="{{providerId}}"/>
                </state>
            </handler>
        </path>
        <path url="/account/add" event="addCustomAccount">
            <route>aw_account_add</route>
            <regex pattern="^/account/add$"/>
            <handler>
                <state route="index.accounts.account-add">
                    <param name="providerId" value="custom"/>
                </state>
            </handler>
        </path>
        <path url="/account/edit/*" event="editAccount">
            <route>aw_account_edit</route>
            <regex pattern="^/account/edit/(\d+)$">
                <set name="accountId" key="1"/>
            </regex>
            <handler>
                <state route="index.accounts.account-edit">
                    <param name="Id" value="a{{accountId}}"/>
                </state>
            </handler>
        </path>
        <path url="/coupon/add" event="addCoupon">
            <route>aw_coupon_add</route>
            <regex pattern="/coupon/add"/>
            <handler>
                <state route="index.accounts.account-add">
                    <param name="providerId" value="coupon"/>
                </state>
            </handler>
        </path>
        <path url="/coupon/edit/*" event="editCoupon">
            <route>aw_coupon_edit</route>
            <regex pattern="^/coupon/edit/(\d+)$">
                <set name="couponId" key="1"/>
            </regex>
            <handler>
                <state route="index.accounts.account-edit">
                    <param name="Id" value="c{{couponId}}"/>
                </state>
            </handler>
        </path>
        <path url="/user/profile" event="profile">
            <route>aw_profile_overview</route>
            <regex pattern="^/user/profile$"/>
            <handler>
                <state route="index.profile"/>
            </handler>
        </path>
        <path url="/user/personal" event="profilePersonalInfo">
            <route>aw_profile_personal</route>
            <regex pattern="^/user/personal$"/>
            <handler>
                <state route="index.profile-edit">
                    <param name="action" value="personal"/>
                </state>
            </handler>
        </path>
        <path url="/user/change-email" event="profileChangeEmail">
            <route>aw_user_change_email</route>
            <regex pattern="^/user/change-email$"/>
            <handler>
                <state route="index.profile-edit">
                    <param name="action" value="changeEmail"/>
                </state>
            </handler>
        </path>
        <path url="/user/change-password-feedback/*" event="profileChangePasswordFeedback">
            <route>aw_profile_change_password_feedback</route>
            <regex pattern="^/user/change-password-feedback/(\d+)/([0-9a-f]{32})$">
                <set name="userId" key="1"/>
                <set name="code" key="2"/>
            </regex>
            <handler>
                <state route="unauth.password-recovery.recovery">
                    <param name="UserId" value="{{userId}}"/>
                    <param name="Hash" value="{{code}}"/>
                </state>
            </handler>
        </path>
        <path url="/*user/change-password" event="profileChangePassword">
            <route>aw_profile_change_password</route>
            <route>aw_profile_change_password_locale</route>
            <regex pattern="^(?:/\w+)?/user/change-password$"/>
            <handler>
                <state route="index.profile-edit">
                    <param name="action" value="changePassword"/>
                </state>
            </handler>
        </path>
        <path url="/user/useCoupon" event="profileUseCoupon" exclude-platform="ios">
            <route>aw_users_usecoupon</route>
            <regex pattern="^/user/useCoupon$"/>
            <handler>
                <state route="index.profile-edit">
                    <param name="action" value="useCoupon"/>
                </state>
            </handler>
        </path>
        <path url="/user/notifications" event="profileNotifications">
            <route>aw_profile_notifications</route>
            <regex pattern="^/user/notifications$"/>
            <handler>
                <state route="index.profile-edit">
                    <param name="action" value="notifications"/>
                </state>
            </handler>
        </path>
        <path url="/user/regional" event="profileRegional">
            <route>aw_profile_regional</route>
            <regex pattern="^/user/regional$"/>
            <handler>
                <state route="index.profile-edit">
                    <param name="action" value="regional"/>
                </state>
            </handler>
        </path>
        <path url="/restore/*" event="profileRestore">
            <route>aw_users_restore_plain</route>
            <regex pattern="^/restore/(.+)$">
                <set name="username" key="1"/>
            </regex>
            <handler>
                <state route="unauth.password-recovery.recovery"/>
            </handler>
        </path>
        <path url="/m/login" event="mobileLogin">
            <regex pattern="^/m/login$"/>
            <handler>
                <state route="unauth.login"/>
            </handler>
        </path>
        <path url="/m/registration" event="mobileRegister">
            <regex pattern="^/m/registration$"/>
            <handler>
                <state route="unauth.registration"/>
            </handler>
        </path>
        <path url="/m/password-recovery/*/*" event="mobilePasswordRecovery">
            <regex pattern="^/m/password-recovery/(\d+)/([0-9a-f]{32})$">
                <set name="userId" key="1"/>
                <set name="code" key="2"/>
            </regex>
            <handler>
                <state route="unauth.password-recovery.recovery">
                    <param name="UserId" value="{{userId}}"/>
                    <param name="Hash" value="{{code}}"/>
                </state>
            </handler>
        </path>
        <path url="/m/password-recovery" event="mobilePasswordRecoveryForm">
            <regex pattern="^/m/password-recovery$"/>
            <handler>
                <state route="unauth.password-recovery"/>
            </handler>
        </path>
        <path url="/m/about" event="mobileAbout">
            <regex pattern="^/m/about$"/>
            <handler>
                <state route="unauth.about"/>
            </handler>
        </path>
        <path url="/m/privacy" event="mobilePrivacy">
            <regex pattern="^/m/privacy$"/>
            <handler>
                <state route="unauth.privacy"/>
            </handler>
        </path>
